### ISSUE TITLE
start issue

### ISSUE THREAD

**Issue by x123y123** [ukhov79/Jetson-Nano-CSI-Stereo-Vision#1]
when I run start.py, I need to run with "sudo python3 start.py".
I only insert "python3 start.py" it can't get image data from imx219.
And I already use "chmod 777" to open video port permission and start.py permission, it still need to use sudo to run start.py....

**Comment by ukhov79** [comment]
Thanks, I added it to the readme.
I’ve been doing this for quite a long time, so I can’t check all the details now.
